Contacts/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Contacts.Controllers
{
    using Services;
    using et = Data.Entities;
    using map = Services.Entities;

    public class ContactsController : Controller
    {
        public ContactsController()
        {
            _contactService = new ContactsService();
        }
        // GET: Contacts
        public ActionResult Index()
        {
            return View(model: _contactService.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(et::Contact contact)
        {
            if(!ModelState.IsValid)
            {
                return View(contact);
            }
            _contactService.CreateContact(new map::Contact { Id = contact.Id, Number = contact.Number});
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            _contactService.DeleteContact(id);
            return RedirectToAction("Index");
        }

        private readonly IContactsService _contactService;
    }
}

Contacts/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Contacts.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Contacts/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Contacts.Services.Entities;
using Contacts.Services;
using System.ComponentModel.DataAnnotations;

namespace Contacts.Controllers
{
    public class PeopleController : Controller
    {
        public PeopleController()
        {
            _peopleService = new PeopleService();
            _contactsService = new ContactsService();
        }
        // GET: People
        public ActionResult Index()
        {
            return View(model: _peopleService.GetAll());
        }

        public ActionResult Create()
        {
            return View(model: new CreatePersonVm()
            {
                FirstName = "",
                LastName = "",
                PreloadedContacts = _contactsService.GetAllNotUsed()
            });
        }

        [HttpPost]
        public ActionResult Create(CreatePersonVm vm)
        {
            if (!ModelState.IsValid)
            {
                vm.PreloadedContacts = _contactsService.GetAllNotUsed();
                return View(vm);
            }

            _peopleService.CreatePerson(
                firstName: vm.FirstName,
                lastName: vm.LastName,
                selectedContacts: vm.SelectedContacts);

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            _peopleService.DeletePerson(id);
            return RedirectToAction("Index");
        }

        private readonly IPeopleService _peopleService;
        private readonly IContactsService _contactsService;

     
    }

    public class CreatePersonVm
    {
        [Required()]
        public string               FirstName               { get; set; }
        [Required()]
        public string               LastName                { get; set; }

        public IEnumerable<Contact> PreloadedContacts       { get; set; }

        public IEnumerable<int> SelectedContacts            { get; set; }
    }
}

Contacts/Views/Contacts/Create.cshtml
@model Contacts.Data.Entities.Contact

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { AllowHtmlAttribute = new { @class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Number, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Contacts/Views/Contacts/Index.cshtml
@model IEnumerable<Contacts.Services.Entities.Contact>

@{
    ViewBag.Title = "Contacts";
}

<h2>Contacts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@foreach(var item in Model)
{
    <div>
        @Html.DisplayFor(modelItem => item.Number) <br />

        @using (Html.BeginForm("Delete", "Contacts", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div>
                <input name="id" value="@item.Id" hidden />
                <input type="submit" value="Delete" class="btn btn-default"/>
            </div>
        }
    </div>
}

Contacts/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Contacts/Views/People/Create.cshtml
@model Contacts.Controllers.CreatePersonVm
@{
    ViewBag.Title = "Create a new person";
}

<h2>Create a new person</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-10">
                <h3>Contacts</h3>
                @Html.ListBoxFor(model => model.SelectedContacts, new MultiSelectList(Model.PreloadedContacts, "Id", "Number"))
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" /> 
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Contacts/Views/People/Index.cshtml
@using map = Contacts.Services.Entities;
@model IEnumerable<map::Person>
@{
    ViewBag.Title = "Index";
}

<h2>People</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<hr />

@foreach (var person in Model)
{
    <div class="well">
        <h3>@person.FirstName</h3>
        <h3>@person.LastName</h3>
        <h4>Contacts</h4>
        @if (person.Contacts.Any())
        {
            foreach (var contact in person.Contacts)
            {
                <h5>@contact.Number</h5>
            }
        }
    </div>

    using (Html.BeginForm("Delete", "People", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div>
            <input name="id" value="@person.Id" hidden />
            <input type="submit" value="Delete" class="btn btn-primary" />
        </div>
    }
    <hr />
}

Contacts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contacts", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("People", "Index", "People")</li>
                    <li>@Html.ActionLink("Contacts", "Index", "Contacts")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Contacts</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>